export const userList = [
    {
        fullName: '',
        profileURL: 'https://lh3.googleusercontent.com/a/ACg8ocK1y98UjB9yWFRumvC19411Uz6LBIgm9NKzJvUsn_8p4UiNUoc=s96-c',
        jobPosition: 'UI Designer',
        name: 'โดนัท',
        status: 'NO_REGIST',
        email: 'pre.register5@checkin.com',
        phoneNumber: '',
        googleId: '',
        allowFindLocation: 0,
        role: 'USER',
        employmentType: 'Company Employee',
        id: '1E0oyrembS9DvwW7JydP',
    },
    {
        allowFindLocation: 0,
        email: 'patiphan.wa@gmail.com',
        jobPosition: 'Front-End',
        status: 'APPROVE',
        employmentType: 'Company Employee',
        googleId: '111547067079422404518',
        profileURL: '',
        phoneNumber: '0970186470',
        role: 'USER',
        fullName: 'Patiphan Wilaiphit',
        name: 'เวฟ',
        id: '6sLuYI7d89B2CrP54I8p',
    },
    {
        profileURL: 'https://lh3.googleusercontent.com/a/ACg8ocJEiU0K9o_bfSwXonfXBYSwOGHwaEEZmPI80Cv_ooNhF4sNrGFh=s96-c',
        phoneNumber: '0619651785',
        googleId: '115717476819625119380',
        name: 'เจเจ',
        email: 'supacharn.kaowanan@gmail.com',
        fullName: 'Supacharn Kaowanan',
        jobPosition: 'Front-End',
        employmentType: 'Intern',
        allowFindLocation: 0,
        role: 'USER',
        status: 'APPROVE',
        id: 'D1MfVvEHvuaNEf4m4uyo',
    },
    {
        role: 'USER',
        name: 'แพร',
        allowFindLocation: 0,
        status: 'APPROVE',
        phoneNumber: '',
        jobPosition: 'Front-End',
        email: 'pearpitchaporn@gmail.com',
        googleId: '100557811553068873527',
        employmentType: 'Company Employee',
        fullName: 'พิชชาพร จันท์โชติกุล',
        profileURL: '',
        id: 'EvDHxAMyUdTw3e1guhPG',
    },
    {
        fullName: '',
        phoneNumber: '',
        status: 'NO_REGIST',
        name: 'น้ำ',
        email: 'nutchanat.nsr@gmail.com',
        profileURL: '',
        allowFindLocation: 0,
        jobPosition: 'Front-End',
        employmentType: 'Company Employee',
        googleId: '',
        role: 'USER',
        id: 'Fe30eDxBnnsT47keGXCr',
    },
    {
        status: 'NO_REGIST',
        fullName: '',
        profileURL: '',
        allowFindLocation: 0,
        role: 'USER',
        phoneNumber: '',
        jobPosition: 'Back-End',
        name: 'รักษ์',
        email: 'Rakgorak@gmail.com',
        employmentType: 'Company Employee',
        googleId: '',
        id: 'KqsOPfOCEgFSjWOPfQBG',
    },
    {
        name: 'UBFor',
        fullName: 'Academy',
        employmentType: 'Company Employee',
        phoneNumber: '0887772955',
        googleId: '113844255012024153757',
        role: 'USER',
        email: 'khawkriab.game@gmail.com',
        profileURL: 'https://lh3.googleusercontent.com/a/ACg8ocLB8C7nf9a-o6GslvuZGwlLRgaMcE8ioYyCSRUH8iTl6u1z1ts=s96-c',
        jobPosition: 'Back-End',
        status: 'WAITING',
        id: 'XUsTDHgd2u63SP28ctXl',
    },
    {
        name: 'เอ็ม',
        fullName: '',
        role: 'USER',
        status: 'NO_REGIST',
        phoneNumber: '',
        profileURL: '',
        allowFindLocation: 0,
        email: 'm.teerapolph@gmail.com',
        googleId: '',
        jobPosition: 'Back-End',
        employmentType: 'Company Employee',
        id: 'eHs7vX0I1RJL9Y7Dadmc',
    },
    {
        profileURL: '',
        email: 'chettaphon.contact@gmail.com',
        employmentType: 'Company Employee',
        jobPosition: 'Back-End',
        googleId: '114162045479402567217',
        allowFindLocation: 0,
        fullName: 'Chettaphon Madwangseang',
        phoneNumber: '0986858781',
        role: 'STAFF',
        name: 'หนึ่ง',
        status: 'APPROVE',
        id: 'nxTbZhR5mfGNuZGYiE1r',
    },
    {
        phoneNumber: '',
        fullName: '',
        employmentType: 'Intern',
        status: 'NO_REGIST',
        jobPosition: 'Back-End',
        profileURL: '',
        allowFindLocation: 0,
        role: 'USER',
        email: 'pre.register3@checkin.com',
        id: 'ofzn6lVf02zWNbB5y486',
        name: 'น้ำอุ่น',
        googleId: '',
    },
    {
        allowFindLocation: 0,
        fullName: '',
        name: 'เด็ดเดี่ยว',
        jobPosition: 'Front-End',
        googleId: '',
        phoneNumber: '',
        employmentType: 'Company Employee',
        profileURL: '',
        status: 'NO_REGIST',
        email: 'akaratsiriwat@gmail.com',
        role: 'USER',
        id: 'pEP8oovaOcwKeT0aCAiC',
    },
    {
        fullName: '',
        allowFindLocation: 0,
        profileURL: '',
        name: 'ช่อ',
        status: 'NO_REGIST',
        jobPosition: 'Back-End',
        phoneNumber: '',
        email: 'chophaka.chi@gmail.com',
        googleId: '',
        role: 'USER',
        employmentType: 'Company Employee',
        id: 'rZjaJjwstkVTvuG6gA2Z',
    },
    {
        status: 'NO_REGIST',
        googleId: '',
        email: ' big.siravit@gmail.com',
        employmentType: 'Company Employee',
        allowFindLocation: 0,
        phoneNumber: '',
        fullName: '',
        role: 'USER',
        jobPosition: 'Back-End',
        profileURL: '',
        name: 'บิ๊ก',
        id: 'skDTRz9s6gbXMrB79son',
    },
    {
        phoneNumber: '0887772955',
        googleId: '114194861929575502045',
        email: 'khawkriab.dev@gmail.com',
        role: 'ADMIN',
        employmentType: 'Company Employee',
        fullName: 'Sittisak Thainoi',
        jobPosition: 'Front-End',
        profileURL: 'https://lh3.googleusercontent.com/a/ACg8ocK1y98UjB9yWFRumvC19411Uz6LBIgm9NKzJvUsn_8p4UiNUoc=s96-c',
        status: 'APPROVE',
        name: 'กล้า',
        allowFindLocation: 1,
        id: 'uhnouLSg67ZRcEE7CX27',
    },
    {
        profileURL: '',
        fullName: '',
        name: 'ป้อง',
        allowFindLocation: 0,
        googleId: '',
        employmentType: 'Intern',
        id: 'v72O6yCXRvEn7Ueaezxm',
        jobPosition: 'Front-End',
        role: 'USER',
        phoneNumber: '',
        email: 'pre.register4@checkin.com',
        status: 'NO_REGIST',
    },
    {
        jobPosition: 'Back-End',
        status: 'NO_REGIST',
        googleId: '',
        email: 'pre.register1@checkin.com',
        employmentType: 'Company Employee',
        profileURL: '',
        phoneNumber: '',
        role: 'USER',
        fullName: '',
        id: 'vuVTCcNrppw5J7aCSaQ0',
        allowFindLocation: 0,
        name: 'ออส',
    },
    {
        role: 'USER',
        phoneNumber: '',
        googleId: '',
        status: 'NO_REGIST',
        jobPosition: 'Back-End',
        email: 'w.chawanut@kkumail.com',
        allowFindLocation: 0,
        name: 'เอิร์ธ',
        employmentType: 'Company Employee',
        profileURL: '',
        fullName: '',
        id: 'wIRqrlPAto3hYZupZCtO',
    },
];
